# Generated by Django 4.2.6 on 2023-10-07 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0004_alter_department_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=50, verbose_name='name')),
                ('lastname', models.CharField(max_length=50, verbose_name='lastName')),
                ('job', models.CharField(choices=[('0', 'Ingeniero'), ('1', 'Arquitecto'), ('2', 'Desarrollador'), ('3', 'Programador')], max_length=1, verbose_name='job')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
            ],
        ),
    ]
