# Generated by Django 4.2.6 on 2023-10-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_skills_alter_employer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='skills',
            field=models.ManyToManyField(to='employer.skills'),
        ),
    ]
