# Generated by Django 4.2.6 on 2023-10-07 16:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_employer_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='cv',
            field=ckeditor.fields.RichTextField(blank=True, default='None'),
        ),
    ]
