# Generated by Django 5.1.2 on 2024-10-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_alter_employer_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='empleados'),
        ),
    ]
