# Generated by Django 4.2.6 on 2023-10-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_alter_department_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(editable=False, max_length=50, verbose_name='name'),
        ),
    ]
