# Generated by Django 4.2.6 on 2023-10-07 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_alter_department_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'short_name')},
        ),
    ]
